name: 'build-test'
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  build:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN}}
          create-if-missing: true
          synced-clubhouse-labels: |
            [
              "📖 doc"
            ]
          label-ch-gh-map: |
            {
              "📖 doc": "documentation"
            }
